{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "en-AU",
    "discourageImplicitMeasures": true,
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/edpprdsqldw00 database windows net;edpprddb",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "edpprdsqldw00.database.windows.net",
            "database": "edpprddb"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "OAuth2",
          "kind": "SQL",
          "path": "edpprdsqldw00.database.windows.net;edpprddb",
          "Expires": "Thu, 30 Jul 2020 16:07:58 GMT",
          "RefreshToken": "********"
        }
      }
    ],
    "tables": [
      {
        "name": "DimChannel",
        "columns": [
          {
            "name": "ChannelSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ChannelSK"
          },
          {
            "name": "ChannelName",
            "dataType": "string",
            "sourceColumn": "ChannelName"
          },
          {
            "name": "ChannelType",
            "dataType": "string",
            "sourceColumn": "ChannelType"
          },
          {
            "name": "ChannelDirection",
            "dataType": "string",
            "sourceColumn": "ChannelDirection"
          },
          {
            "name": "SourceSystem",
            "dataType": "string",
            "sourceColumn": "SourceSystem"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/edpprdsqldw00 database windows net;edpprddb\",",
                "    sp_commercial_dimChannel = Source{[Schema=\"sp_commercial\",Item=\"dimChannel\"]}[Data]",
                "in",
                "    sp_commercial_dimChannel"
              ]
            }
          }
        ]
      },
      {
        "name": "DimCustomerJourney",
        "columns": [
          {
            "name": "CustJourneySK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustJourneySK"
          },
          {
            "name": "JourneyType",
            "dataType": "string",
            "sourceColumn": "JourneyType"
          },
          {
            "name": "JourneyName",
            "dataType": "string",
            "sourceColumn": "JourneyName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/edpprdsqldw00 database windows net;edpprddb\",",
                "    sp_commercial_dimCustJourney = Source{[Schema=\"sp_commercial\",Item=\"dimCustJourney\"]}[Data]",
                "in",
                "    sp_commercial_dimCustJourney"
              ]
            }
          }
        ]
      },
      {
        "name": "DimProduct",
        "columns": [
          {
            "name": "ProductSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductSK"
          },
          {
            "name": "ProductId",
            "dataType": "string",
            "sourceColumn": "ProductId"
          },
          {
            "name": "ProductCategory",
            "dataType": "string",
            "sourceColumn": "ProductCategory"
          },
          {
            "name": "ProductName",
            "dataType": "string",
            "sourceColumn": "ProductName"
          },
          {
            "name": "ProductType",
            "dataType": "string",
            "sourceColumn": "ProductType"
          },
          {
            "name": "ProductDescription",
            "dataType": "string",
            "sourceColumn": "ProductDescription"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/edpprdsqldw00 database windows net;edpprddb\",",
                "    sp_commercial_dimProduct = Source{[Schema=\"sp_commercial\",Item=\"dimProduct\"]}[Data]",
                "in",
                "    sp_commercial_dimProduct"
              ]
            }
          }
        ]
      },
      {
        "name": "DimProposition",
        "columns": [
          {
            "name": "PropositionSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PropositionSK"
          },
          {
            "name": "PropositionName",
            "dataType": "string",
            "sourceColumn": "PropositionName"
          },
          {
            "name": "PropositionControlGroup",
            "dataType": "string",
            "sourceColumn": "PropositionControlGroup"
          },
          {
            "name": "PropositionStrategicObjective",
            "dataType": "string",
            "sourceColumn": "PropositionStrategicObjective"
          },
          {
            "name": "PropositionStrategy",
            "dataType": "string",
            "sourceColumn": "PropositionStrategy"
          },
          {
            "name": "PropositionTreatment",
            "dataType": "string",
            "sourceColumn": "PropositionTreatment"
          },
          {
            "name": "PropositionInitiative",
            "dataType": "string",
            "sourceColumn": "PropositionInitiative"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/edpprdsqldw00 database windows net;edpprddb\",",
                "    sp_commercial_dimProposition = Source{[Schema=\"sp_commercial\",Item=\"dimProposition\"]}[Data]",
                "in",
                "    sp_commercial_dimProposition"
              ]
            }
          }
        ]
      },
      {
        "name": "DimTouchPoint",
        "columns": [
          {
            "name": "TouchPointSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TouchPointSK"
          },
          {
            "name": "TouchPointType",
            "dataType": "string",
            "sourceColumn": "TouchPointType"
          },
          {
            "name": "TouchPointName",
            "dataType": "string",
            "sourceColumn": "TouchPointName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/edpprdsqldw00 database windows net;edpprddb\",",
                "    sp_commercial_dimTouchPoint = Source{[Schema=\"sp_commercial\",Item=\"dimTouchPoint\"]}[Data]",
                "in",
                "    sp_commercial_dimTouchPoint"
              ]
            }
          }
        ]
      },
      {
        "name": "DimLocation",
        "columns": [
          {
            "name": "LocationSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "LocationSK"
          },
          {
            "name": "PostCode",
            "dataType": "string",
            "sourceColumn": "PostCode"
          },
          {
            "name": "Suburb",
            "dataType": "string",
            "sourceColumn": "Suburb"
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/edpprdsqldw00 database windows net;edpprddb\",",
                "    sp_open_dimLocation = Source{[Schema=\"sp_open\",Item=\"dimLocation\"]}[Data]",
                "in",
                "    sp_open_dimLocation"
              ]
            }
          }
        ]
      },
      {
        "name": "DimCampaign",
        "columns": [
          {
            "name": "CampaignSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CampaignSK"
          },
          {
            "name": "CampaignCategory",
            "dataType": "string",
            "sourceColumn": "CampaignCategory"
          },
          {
            "name": "CampaignName",
            "dataType": "string",
            "sourceColumn": "CampaignName"
          },
          {
            "name": "CampaignLabel",
            "dataType": "string",
            "sourceColumn": "CampaignLabel"
          },
          {
            "name": "CampaignDuration",
            "dataType": "int64",
            "sourceColumn": "CampaignDuration"
          },
          {
            "name": "CampaignStartDate",
            "dataType": "dateTime",
            "sourceColumn": "CampaignStartDate"
          },
          {
            "name": "CampaignEndDate",
            "dataType": "dateTime",
            "sourceColumn": "CampaignEndDate"
          },
          {
            "name": "CampaignStrategicObjective",
            "dataType": "string",
            "sourceColumn": "CampaignStrategicObjective"
          },
          {
            "name": "CampaignStrategy",
            "dataType": "string",
            "sourceColumn": "CampaignStrategy"
          },
          {
            "name": "CampaignTreatment",
            "dataType": "string",
            "sourceColumn": "CampaignTreatment"
          },
          {
            "name": "CampaignInitiative",
            "dataType": "string",
            "sourceColumn": "CampaignInitiative"
          },
          {
            "name": "CampaignControlGroup",
            "dataType": "string",
            "sourceColumn": "CampaignControlGroup"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/edpprdsqldw00 database windows net;edpprddb\",",
                "    sp_commercial_dimCampaign = Source{[Schema=\"sp_commercial\",Item=\"dimCampaign\"]}[Data]",
                "in",
                "    sp_commercial_dimCampaign"
              ]
            }
          }
        ]
      },
      {
        "name": "CalculationGroup 1",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "CalculationItem 1"
            }
          ]
        },
        "columns": [
          {
            "name": "CalculationItemColumn 1",
            "dataType": "string",
            "sourceColumn": "Name"
          }
        ],
        "partitions": [
          {
            "name": "CalculationGroup 1",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "DimDate",
        "columns": [
          {
            "name": "DateSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DateSK"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date"
          },
          {
            "name": "FullDate",
            "dataType": "string",
            "sourceColumn": "FullDate"
          },
          {
            "name": "DayOfMonth",
            "dataType": "string",
            "sourceColumn": "DayOfMonth"
          },
          {
            "name": "DaySuffix",
            "dataType": "string",
            "sourceColumn": "DaySuffix"
          },
          {
            "name": "DayName",
            "dataType": "string",
            "sourceColumn": "DayName"
          },
          {
            "name": "DayOfWeek",
            "dataType": "string",
            "sourceColumn": "DayOfWeek"
          },
          {
            "name": "DayOfWeekInMonth",
            "dataType": "string",
            "sourceColumn": "DayOfWeekInMonth"
          },
          {
            "name": "DayOfWeekInYear",
            "dataType": "string",
            "sourceColumn": "DayOfWeekInYear"
          },
          {
            "name": "DayOfQuarter",
            "dataType": "string",
            "sourceColumn": "DayOfQuarter"
          },
          {
            "name": "DayOfYear",
            "dataType": "string",
            "sourceColumn": "DayOfYear"
          },
          {
            "name": "WeekOfMonth",
            "dataType": "string",
            "sourceColumn": "WeekOfMonth"
          },
          {
            "name": "WeekOfQuarter",
            "dataType": "string",
            "sourceColumn": "WeekOfQuarter"
          },
          {
            "name": "WeekOfYear",
            "dataType": "string",
            "sourceColumn": "WeekOfYear"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month"
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "sourceColumn": "MonthName"
          },
          {
            "name": "MonthOfQuarter",
            "dataType": "string",
            "sourceColumn": "MonthOfQuarter"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter"
          },
          {
            "name": "QuarterName",
            "dataType": "string",
            "sourceColumn": "QuarterName"
          },
          {
            "name": "Year",
            "dataType": "string",
            "sourceColumn": "Year"
          },
          {
            "name": "YearName",
            "dataType": "string",
            "sourceColumn": "YearName"
          },
          {
            "name": "MonthYear",
            "dataType": "string",
            "sourceColumn": "MonthYear"
          },
          {
            "name": "MMYYYY",
            "dataType": "string",
            "sourceColumn": "MMYYYY"
          },
          {
            "name": "FirstDayOfMonth",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfMonth"
          },
          {
            "name": "LastDayOfMonth",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfMonth"
          },
          {
            "name": "FirstDayOfQuarter",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfQuarter"
          },
          {
            "name": "LastDayOfQuarter",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfQuarter"
          },
          {
            "name": "FirstDayOfYear",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfYear"
          },
          {
            "name": "LastDayOfYear",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfYear"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/edpprdsqldw00 database windows net;edpprddb\",",
                "    sp_open_dimDate = Source{[Schema=\"sp_open\",Item=\"dimDate\"]}[Data]",
                "in",
                "    sp_open_dimDate"
              ]
            }
          }
        ]
      },
      {
        "name": "FactCustomerMetrics",
        "columns": [
          {
            "name": "ActualCustMetricFactSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ActualCustMetricFactSK"
          },
          {
            "name": "PropositionSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PropositionSK"
          },
          {
            "name": "CampaignSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CampaignSK"
          },
          {
            "name": "LocationSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "LocationSK"
          },
          {
            "name": "DateSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DateSK"
          },
          {
            "name": "TimeSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TimeSK"
          },
          {
            "name": "ChannelSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ChannelSK"
          },
          {
            "name": "ProductSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductSK"
          },
          {
            "name": "CustJourneySK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustJourneySK"
          },
          {
            "name": "CustomerSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerSK"
          },
          {
            "name": "TouchPointSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TouchPointSK"
          },
          {
            "name": "EmailFailCount",
            "dataType": "int64",
            "sourceColumn": "EmailFailCount"
          },
          {
            "name": "EmailSentCount",
            "dataType": "int64",
            "sourceColumn": "EmailSentCount"
          },
          {
            "name": "EmailDeliveryCount",
            "dataType": "int64",
            "sourceColumn": "EmailDeliveryCount"
          },
          {
            "name": "EmailPendingCount",
            "dataType": "int64",
            "sourceColumn": "EmailPendingCount"
          },
          {
            "name": "EmailDeliveryDateTime",
            "dataType": "dateTime",
            "sourceColumn": "EmailDeliveryDateTime"
          },
          {
            "name": "EmailFailDateTime",
            "dataType": "dateTime",
            "sourceColumn": "EmailFailDateTime"
          },
          {
            "name": "EmailSentDateTime",
            "dataType": "dateTime",
            "sourceColumn": "EmailSentDateTime"
          },
          {
            "name": "SMSCount",
            "dataType": "int64",
            "sourceColumn": "SMSCount"
          },
          {
            "name": "DMCount",
            "dataType": "int64",
            "sourceColumn": "DMCount"
          },
          {
            "name": "OTMCount",
            "dataType": "int64",
            "sourceColumn": "OTMCount"
          },
          {
            "name": "TouchPointDateTime",
            "dataType": "dateTime",
            "sourceColumn": "TouchPointDateTime"
          },
          {
            "name": "EmailClickCount",
            "dataType": "int64",
            "sourceColumn": "EmailClickCount"
          },
          {
            "name": "EmailOpenCount",
            "dataType": "int64",
            "sourceColumn": "EmailOpenCount"
          },
          {
            "name": "EmailMirrorPageCount",
            "dataType": "int64",
            "sourceColumn": "EmailMirrorPageCount"
          },
          {
            "name": "EmailClickDateTime",
            "dataType": "dateTime",
            "sourceColumn": "EmailClickDateTime"
          },
          {
            "name": "EmailOpenDateTime",
            "dataType": "dateTime",
            "sourceColumn": "EmailOpenDateTime"
          },
          {
            "name": "URLLabel",
            "dataType": "string",
            "sourceColumn": "URLLabel"
          },
          {
            "name": "EmailOptOut",
            "dataType": "int64",
            "sourceColumn": "EmailOptOut"
          },
          {
            "name": "ImpressionCountMobile",
            "dataType": "int64",
            "sourceColumn": "ImpressionCountMobile"
          },
          {
            "name": "ImpressionClickCountMobile",
            "dataType": "int64",
            "sourceColumn": "ImpressionClickCountMobile"
          },
          {
            "name": "ImpressionCountMyAccount",
            "dataType": "int64",
            "sourceColumn": "ImpressionCountMyAccount"
          },
          {
            "name": "ImpressionClickCountMyAccount",
            "dataType": "int64",
            "sourceColumn": "ImpressionClickCountMyAccount"
          },
          {
            "name": "ImpressionCountWeb",
            "dataType": "int64",
            "sourceColumn": "ImpressionCountWeb"
          },
          {
            "name": "ImpressionClickCountWeb",
            "dataType": "int64",
            "sourceColumn": "ImpressionClickCountWeb"
          },
          {
            "name": "ImpressionCountSocial",
            "dataType": "int64",
            "sourceColumn": "ImpressionCountSocial"
          },
          {
            "name": "ImpressionClickCountSocial",
            "dataType": "int64",
            "sourceColumn": "ImpressionClickCountSocial"
          },
          {
            "name": "ImpressionDateTime",
            "dataType": "dateTime",
            "sourceColumn": "ImpressionDateTime"
          },
          {
            "name": "ImpressionClickDateTime",
            "dataType": "dateTime",
            "sourceColumn": "ImpressionClickDateTime"
          },
          {
            "name": "ICCRevoked",
            "dataType": "int64",
            "sourceColumn": "ICCRevoked"
          },
          {
            "name": "ICCAccepted",
            "dataType": "int64",
            "sourceColumn": "ICCAccepted"
          },
          {
            "name": "ICCRejected",
            "dataType": "int64",
            "sourceColumn": "ICCRejected"
          },
          {
            "name": "ICCCount",
            "dataType": "int64",
            "sourceColumn": "ICCCount"
          },
          {
            "name": "ICCMaybe",
            "dataType": "int64",
            "sourceColumn": "ICCMaybe"
          },
          {
            "name": "ICCDateTime",
            "dataType": "dateTime",
            "sourceColumn": "ICCDateTime"
          },
          {
            "name": "CurrentStatus",
            "dataType": "string",
            "sourceColumn": "CurrentStatus"
          },
          {
            "name": "CurrentStatusDateTime",
            "dataType": "dateTime",
            "sourceColumn": "CurrentStatusDateTime"
          },
          {
            "name": "PreviousStatus",
            "dataType": "string",
            "sourceColumn": "PreviousStatus"
          },
          {
            "name": "ConversionDateTime",
            "dataType": "dateTime",
            "sourceColumn": "ConversionDateTime"
          },
          {
            "name": "CustomerConversion",
            "dataType": "int64",
            "sourceColumn": "CustomerConversion"
          },
          {
            "name": "JourneyRank",
            "dataType": "int64",
            "sourceColumn": "JourneyRank"
          },
          {
            "name": "TouchPointRank",
            "dataType": "int64",
            "sourceColumn": "TouchPointRank"
          },
          {
            "name": "FuelSold",
            "dataType": "string",
            "sourceColumn": "FuelSold"
          },
          {
            "name": "TargetFuel",
            "dataType": "string",
            "sourceColumn": "TargetFuel"
          },
          {
            "name": "RowInserted",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "RowInserted"
          },
          {
            "name": "RowUpdated",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "RowUpdated"
          },
          {
            "name": "Filter",
            "dataType": "int64",
            "sourceColumn": "Filter"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/edpprdsqldw00 database windows net;edpprddb\",",
                "    sp_commercial_FactCustomerMetrics = Source{[Schema=\"sp_commercial\",Item=\"FactCustomerMetrics\"]}[Data],",
                "    #\"Added Custom\" = Table.AddColumn(sp_commercial_FactCustomerMetrics, \"Filter\", each [PropositionSK]+[CampaignSK]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Filter\", Int64.Type}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each [Filter] <> -2)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "LEADS",
            "expression": " CALCULATE(SUM(FactCustomerMetrics[EmailDeliveryCount]),DimCampaign[CampaignName]=\"agl_XSell_Campaign\",DimChannel[ChannelName]=\"EMAIL\")"
          },
          {
            "name": "TotaleDMsSent",
            "expression": [
              "CALCULATE(SUM(FactCustomerMetrics[EmailSentCount]),DimCampaign[CampaignName]=\"agl_XSell_Campaign\",",
              "DimChannel[ChannelName]=\"EMAIL\")"
            ]
          },
          {
            "name": "TotaleDMsReceived",
            "expression": [
              " CALCULATE(SUM(FactCustomerMetrics[EmailSentCount]),DimCampaign[CampaignName]=\"agl_XSell_Campaign\",",
              "DimChannel[ChannelName]=\"EMAIL\")",
              ""
            ]
          },
          {
            "name": "eDMBounceRate",
            "expression": [
              " CALCULATE(SUM(FactCustomerMetrics[EmailFailCount]),",
              "DimCampaign[CampaignName]=\"agl_XSell_Campaign\",",
              "DimChannel[ChannelName]=\"EMAIL\"",
              ")",
              "/[TotaleDMsReceived]"
            ]
          },
          {
            "name": "UniqueCustomers",
            "expression": " DISTINCTCOUNT(DimTargetCustomer[BPID])"
          },
          {
            "name": "AVGeDMSPerLead",
            "expression": " [TotaleDMsSent]/[LEADS]"
          },
          {
            "name": "TotaleDMsOpen",
            "expression": [
              " CALCULATE(SUM(FactCustomerMetrics[EmailOpenCount]),DimCampaign[CampaignName]=\"agl_XSell_Campaign\",",
              "DimChannel[ChannelName]=\"EMAIL\")",
              ""
            ]
          },
          {
            "name": "TotaleDMsPending",
            "expression": [
              " CALCULATE(SUM(FactCustomerMetrics[EmailPendingCount]),DimCampaign[CampaignName]=\"agl_XSell_Campaign\",",
              "DimChannel[ChannelName]=\"EMAIL\")",
              ""
            ]
          }
        ]
      },
      {
        "name": "DimTime",
        "columns": [
          {
            "name": "TimeSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TimeSK"
          },
          {
            "name": "Hour24",
            "dataType": "int64",
            "sourceColumn": "Hour24"
          },
          {
            "name": "Hour24ShortString",
            "dataType": "string",
            "sourceColumn": "Hour24ShortString"
          },
          {
            "name": "Hour24MinString",
            "dataType": "string",
            "sourceColumn": "Hour24MinString"
          },
          {
            "name": "Hour24FullString",
            "dataType": "string",
            "sourceColumn": "Hour24FullString"
          },
          {
            "name": "Hour12",
            "dataType": "int64",
            "sourceColumn": "Hour12"
          },
          {
            "name": "Hour12ShortString",
            "dataType": "string",
            "sourceColumn": "Hour12ShortString"
          },
          {
            "name": "Hour12MinString",
            "dataType": "string",
            "sourceColumn": "Hour12MinString"
          },
          {
            "name": "Hour12FullString",
            "dataType": "string",
            "sourceColumn": "Hour12FullString"
          },
          {
            "name": "AmPmCode",
            "dataType": "int64",
            "sourceColumn": "AmPmCode"
          },
          {
            "name": "AmPmString",
            "dataType": "string",
            "sourceColumn": "AmPmString"
          },
          {
            "name": "Minute",
            "dataType": "int64",
            "sourceColumn": "Minute"
          },
          {
            "name": "MinuteCode",
            "dataType": "int64",
            "sourceColumn": "MinuteCode"
          },
          {
            "name": "MinuteShortString",
            "dataType": "string",
            "sourceColumn": "MinuteShortString"
          },
          {
            "name": "MinuteFullString24",
            "dataType": "string",
            "sourceColumn": "MinuteFullString24"
          },
          {
            "name": "MinuteFullString12",
            "dataType": "string",
            "sourceColumn": "MinuteFullString12"
          },
          {
            "name": "HalfHour",
            "dataType": "int64",
            "sourceColumn": "HalfHour"
          },
          {
            "name": "HalfHourCode",
            "dataType": "int64",
            "sourceColumn": "HalfHourCode"
          },
          {
            "name": "HalfHourShortString",
            "dataType": "string",
            "sourceColumn": "HalfHourShortString"
          },
          {
            "name": "HalfHourFullString24",
            "dataType": "string",
            "sourceColumn": "HalfHourFullString24"
          },
          {
            "name": "HalfHourFullString12",
            "dataType": "string",
            "sourceColumn": "HalfHourFullString12"
          },
          {
            "name": "FullTimeString24",
            "dataType": "string",
            "sourceColumn": "FullTimeString24"
          },
          {
            "name": "FullTimeString12",
            "dataType": "string",
            "sourceColumn": "FullTimeString12"
          },
          {
            "name": "FullTime",
            "dataType": "dateTime",
            "sourceColumn": "FullTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/edpprdsqldw00 database windows net;edpprddb\",",
                "    sp_open_DimTime = Source{[Schema=\"sp_open\",Item=\"DimTime\"]}[Data]",
                "in",
                "    sp_open_DimTime"
              ]
            }
          }
        ]
      },
      {
        "name": "DimTargetCustomer",
        "columns": [
          {
            "name": "CustomerSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerSK"
          },
          {
            "name": "BPID",
            "dataType": "string",
            "sourceColumn": "BPID"
          },
          {
            "name": "CustomerDOB",
            "dataType": "dateTime",
            "sourceColumn": "CustomerDOB"
          },
          {
            "name": "CustomerGender",
            "dataType": "string",
            "sourceColumn": "CustomerGender"
          },
          {
            "name": "CustomerSoho",
            "dataType": "string",
            "sourceColumn": "CustomerSoho"
          },
          {
            "name": "CustomerSME",
            "dataType": "string",
            "sourceColumn": "CustomerSME"
          },
          {
            "name": "CustomerSMER",
            "dataType": "string",
            "sourceColumn": "CustomerSMER"
          },
          {
            "name": "CustomerRESI",
            "dataType": "string",
            "sourceColumn": "CustomerRESI"
          },
          {
            "name": "CustomerStatus",
            "dataType": "string",
            "sourceColumn": "CustomerStatus"
          },
          {
            "name": "CustomerChurnDate",
            "dataType": "dateTime",
            "sourceColumn": "CustomerChurnDate"
          },
          {
            "name": "CustomerType",
            "dataType": "string",
            "sourceColumn": "CustomerType"
          },
          {
            "name": "ActiveCustomer",
            "dataType": "string",
            "sourceColumn": "ActiveCustomer"
          },
          {
            "name": "CNIFlag",
            "dataType": "string",
            "sourceColumn": "CNIFlag"
          },
          {
            "name": "CompanyFlag",
            "dataType": "string",
            "sourceColumn": "CompanyFlag"
          },
          {
            "name": "AGLRewards",
            "dataType": "string",
            "sourceColumn": "AGLRewards"
          },
          {
            "name": "BusinessMultisite",
            "dataType": "string",
            "sourceColumn": "BusinessMultisite"
          },
          {
            "name": "CustomerSegment",
            "dataType": "string",
            "sourceColumn": "CustomerSegment"
          },
          {
            "name": "CustomerValueState",
            "dataType": "string",
            "sourceColumn": "CustomerValueState"
          },
          {
            "name": "CustomerValueNational",
            "dataType": "string",
            "sourceColumn": "CustomerValueNational"
          },
          {
            "name": "CustomerChurnPropensity",
            "dataType": "string",
            "sourceColumn": "CustomerChurnPropensity"
          },
          {
            "name": "CustomerRiskClass",
            "dataType": "string",
            "sourceColumn": "CustomerRiskClass"
          },
          {
            "name": "CustomerRiskScore",
            "dataType": "int64",
            "sourceColumn": "CustomerRiskScore"
          },
          {
            "name": "ElectricityContracts",
            "dataType": "int64",
            "sourceColumn": "ElectricityContracts"
          },
          {
            "name": "GasContracts",
            "dataType": "int64",
            "sourceColumn": "GasContracts"
          },
          {
            "name": "ClassNoOfSites",
            "dataType": "string",
            "sourceColumn": "ClassNoOfSites"
          },
          {
            "name": "CustomerStartDate",
            "dataType": "dateTime",
            "sourceColumn": "CustomerStartDate"
          },
          {
            "name": "CustomerTenure",
            "dataType": "int64",
            "sourceColumn": "CustomerTenure"
          },
          {
            "name": "MyAccountFlag",
            "dataType": "string",
            "sourceColumn": "MyAccountFlag"
          },
          {
            "name": "LastSuccessfulMyAccountLoginDate",
            "dataType": "dateTime",
            "sourceColumn": "LastSuccessfulMyAccountLoginDate"
          },
          {
            "name": "TotalSuccessfulMyAccountLogins",
            "dataType": "int64",
            "sourceColumn": "TotalSuccessfulMyAccountLogins"
          },
          {
            "name": "Webchatflag",
            "dataType": "string",
            "sourceColumn": "Webchatflag"
          },
          {
            "name": "LastWebchatDate",
            "dataType": "dateTime",
            "sourceColumn": "LastWebchatDate"
          },
          {
            "name": "CustomerHardship",
            "dataType": "string",
            "sourceColumn": "CustomerHardship"
          },
          {
            "name": "OmbudsmanComplaint",
            "dataType": "string",
            "sourceColumn": "OmbudsmanComplaint"
          },
          {
            "name": "StayingConnectedFlag",
            "dataType": "string",
            "sourceColumn": "StayingConnectedFlag"
          },
          {
            "name": "Complaints",
            "dataType": "string",
            "sourceColumn": "Complaints"
          },
          {
            "name": "BadDebt",
            "dataType": "string",
            "sourceColumn": "BadDebt"
          },
          {
            "name": "OutstandingDebt",
            "dataType": "string",
            "sourceColumn": "OutstandingDebt"
          },
          {
            "name": "IncompleteMailingAddress",
            "dataType": "string",
            "sourceColumn": "IncompleteMailingAddress"
          },
          {
            "name": "XsellFlag",
            "dataType": "string",
            "sourceColumn": "XsellFlag"
          },
          {
            "name": "DateFrom",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "DateFrom"
          },
          {
            "name": "DateTo",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "DateTo"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/edpprdsqldw00 database windows net;edpprddb\",",
                "    sp_customer_dimTargetCustomer = Source{[Schema=\"sp_customer\",Item=\"dimTargetCustomer\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(sp_customer_dimTargetCustomer,{\"HashDiff\", \"RowInserted\", \"RowUpdated\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Columns\", each [DateTo] = #date(2050, 12, 31) and [XsellFlag] = \"Y\"),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Filtered Rows\",{\"CustomerAge\"})",
                "in",
                "    #\"Removed Columns1\""
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "fa9c0073-bd72-44bd-a419-45a698bb63a5",
        "fromTable": "FactCustomerMetrics",
        "fromColumn": "DateSK",
        "toTable": "DimDate",
        "toColumn": "Date"
      },
      {
        "name": "42161835-e562-45f0-8c84-9d24700519e4",
        "fromTable": "FactCustomerMetrics",
        "fromColumn": "CampaignSK",
        "toTable": "DimCampaign",
        "toColumn": "CampaignSK"
      },
      {
        "name": "c85cd9f1-c578-4955-a848-16c098a352e7",
        "fromTable": "FactCustomerMetrics",
        "fromColumn": "ChannelSK",
        "toTable": "DimChannel",
        "toColumn": "ChannelSK"
      },
      {
        "name": "6e2ec7d4-cea0-4e39-995c-c01b93fe4356",
        "fromTable": "FactCustomerMetrics",
        "fromColumn": "CustJourneySK",
        "toTable": "DimCustomerJourney",
        "toColumn": "CustJourneySK"
      },
      {
        "name": "11a4120a-8995-4fb5-856b-76fac890b712",
        "fromTable": "FactCustomerMetrics",
        "fromColumn": "LocationSK",
        "toTable": "DimLocation",
        "toColumn": "LocationSK"
      },
      {
        "name": "aac3f01e-c409-4c5f-93d3-0913f52e6605",
        "fromTable": "FactCustomerMetrics",
        "fromColumn": "PropositionSK",
        "toTable": "DimProposition",
        "toColumn": "PropositionSK"
      },
      {
        "name": "73f235af-f4a7-4cf2-99e3-95100698b46d",
        "fromTable": "FactCustomerMetrics",
        "fromColumn": "CustomerSK",
        "toTable": "DimTargetCustomer",
        "toColumn": "CustomerSK",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "2bed8988-166b-47ad-9bc3-d141f2921da5",
        "fromTable": "FactCustomerMetrics",
        "fromColumn": "TimeSK",
        "toTable": "DimTime",
        "toColumn": "TimeSK"
      },
      {
        "name": "d522eb00-90f8-4d74-a60a-cf9f57b9d510",
        "fromTable": "FactCustomerMetrics",
        "fromColumn": "TouchPointSK",
        "toTable": "DimTouchPoint",
        "toColumn": "TouchPointSK"
      },
      {
        "name": "aed1e23c-5c96-44da-baa2-7b068391e396",
        "fromTable": "FactCustomerMetrics",
        "fromColumn": "ProductSK",
        "toTable": "DimProduct",
        "toColumn": "ProductSK"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}